# Generated by Django 6.0.2 on 2026-04-23 05:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0006_channel_color_channel_emoji'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomPomodoroSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('running', 'Running'), ('paused', 'Paused'), ('break', 'Break'), ('completed', 'Completed')], default='not_started', max_length=20)),
                ('session_duration', models.PositiveIntegerField(default=25)),
                ('break_duration', models.PositiveIntegerField(default=5)),
                ('cycles_completed', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_muted', models.BooleanField(default=False)),
                ('room', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pomodoro_session', to='rooms.studyroom')),
                ('started_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='started_pomodoro_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
