# Generated by Django 6.0.2 on 2026-04-23 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0007_roompomodorosession'),
        ('rooms', '0009_messagemention_messagereadstatus'),
    ]

    operations = [
    ]
