# Generated by Django 6.0.2 on 2026-04-21 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0005_task_description_task_source_message_task_updated_at_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="userprofile",
            old_name="avatar",
            new_name="profile_image",
        ),
        migrations.RemoveField(
            model_name="user",
            name="profile_picture",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="profile_pic",
        ),
    ]
