# Generated by Django 6.0.2 on 2026-04-23 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_userprofile_connection_count_userprofile_is_online_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='connection_count',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
